### ISSUE TITLE
Beeblex stopped using Sandbox

### ISSUE THREAD

**Issue by Ghirigoro** [BlueParabola/Beeblex-SDK#5]
I have a project that is still in development and uses the sandbox for all purchases. I integrated Beeblex and everything worked fine for the last few days. Starting this afternoon all transactions were being flagged as invalid. I checked the transactions in the debugger and noticed that the usesSandbox property was set to NO. After manually assigning it to yes transactions started coming in as valid again. I'm not sure exactly how developers are supposed to manage the sandbox (and let me know if I'm just missing something that was in docs) but it seems like either we have to always explicitly set the property ourselves or the system should manage that in a consistent way (e.g. all debug builds use the sandbox and all release use the regular store).

**Comment by mtabini** [comment]
Hi there!

It might have actually been something on Apple's side. We had a similar problem with two of our apps (including one that doesn't yet use Beeblex), where receipts were being validated by both the sandbox and live server regardless of where they originated from, and then the system started working properly again. So, that might have been it.

The useSandbox property is meant to be set to NO by default; we consider this to be the “safe” pattern, because it forces you to proactively switch to the sandbox and become aware of the setting. If we set it to YES by default, there's a risk that you would never learn the setting exists, push the app to the iTS and then find out that all requests are going to the sandbox. (Of course, this is still possible, because you can forget to set it to NO before submitting; but that's why we have the “Ignore Sandbox” setting on the Website).

Setting the flag to YES by default builds and to NO on release builds seems a little dangerous. When you distribute betas to your testers using the Archive function, those are likely to be built using the release configuration, and so your testers would have all their receipts rejected, while you would not experience the same when you build & run locally using the debug configuration, leading to much more frustration than a developer is going to want to deal with :-)

**Comment by Ghirigoro** [comment]
Ok thanks for clearing that up. You're right and I absolutely agree about ad-hoc builds. I misspoke when referring to debug vs. release builds and should have said development and app store distribution builds.https://github.com/BlueParabola/Beeblex-SDK/issues/5/close
